spring:
    application:
        name: jwttoken
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Mmogluk57.
        url: jdbc:mysql://localhost:3306/jwt_security
        username: springstudent
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
        show-sql: true
logging:
    level:
        org.springframework.security: TRACE
